# Generated by Django 4.1.7 on 2023-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_image_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
